import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawn, exec } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

const BASE_DIR = __dirname;
const STORAGE_DIR = path.join(BASE_DIR, 'storage');
const DB_FILE = path.join(STORAGE_DIR, 'videos_db.json');
const GENRES_FILE = path.join(BASE_DIR, 'video_engine', 'genres_config.json');
const SECRETS_FILE = path.join(BASE_DIR, 'client_secrets.json');
const ENV_FILE = path.join(BASE_DIR, '.env');

// Serve generated media static files
app.use('/videos', express.static(path.join(STORAGE_DIR, 'output_videos')));
app.use('/thumbnails', express.static(path.join(STORAGE_DIR, 'output_thumbnails')));

// In-Memory Automation State & System Logs
let automationState = {
  active: false,
  intervalMinutes: 15,
  strategy: 'sequential', // 'sequential', 'random'
  privacy: 'unlisted',
  autoUpload: true,
  selectedGenres: ['history', 'kids', 'languages', 'trending', 'politics', 'scifi', 'scary'],
  currentGenreIndex: 0,
  lastRunTime: null,
  nextRunTime: null,
  totalAutoGenerated: 0
};

let systemLogs = [
  { timestamp: new Date().toISOString(), message: "YouTube Continuous Automation System Initialized.", level: "info" }
];

function addLog(message, level = "info") {
  const logItem = { timestamp: new Date().toISOString(), message, level };
  systemLogs.unshift(logItem);
  if (systemLogs.length > 200) systemLogs.pop();
  console.log(`[${logItem.timestamp}] [${level.toUpperCase()}] ${message}`);
}

function readJsonFile(filePath, fallback = []) {
  if (fs.existsSync(filePath)) {
    try {
      return JSON.parse(fs.readFileSync(filePath, 'utf8'));
    } catch (e) {
      console.error(`Error reading ${filePath}:`, e);
    }
  }
  return fallback;
}

function writeJsonFile(filePath, data) {
  try {
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  } catch (e) {
    console.error(`Error writing ${filePath}:`, e);
  }
}

// System Status Endpoint
app.get('/api/status', (req, res) => {
  const videos = readJsonFile(DB_FILE, []);
  const genres = readJsonFile(GENRES_FILE, []);

  const genreStats = {};
  genres.forEach(g => { genreStats[g.id] = 0; });
  videos.forEach(v => {
    if (genreStats[v.genreId] !== undefined) {
      genreStats[v.genreId]++;
    } else {
      genreStats[v.genreId] = 1;
    }
  });

  res.json({
    totalVideos: videos.length,
    uploadedCount: videos.filter(v => v.status === 'uploaded' || v.status === 'uploaded_simulated').length,
    automation: automationState,
    genreStats,
    hasOAuthSecrets: fs.existsSync(SECRETS_FILE),
    hasLlmKey: fs.existsSync(ENV_FILE)
  });
});

// Genres Endpoints
app.get('/api/genres', (req, res) => {
  const genres = readJsonFile(GENRES_FILE, []);
  res.json(genres);
});

app.post('/api/genres', (req, res) => {
  const updatedGenres = req.body;
  writeJsonFile(GENRES_FILE, updatedGenres);
  addLog("Genres configuration updated successfully.", "success");
  res.json({ success: true, genres: updatedGenres });
});

// Videos Database Endpoints
app.get('/api/videos', (req, res) => {
  const videos = readJsonFile(DB_FILE, []);
  res.json(videos);
});

// Video Generator API Trigger
app.post('/api/generate', (req, res) => {
  const { genreId, topic, privacy = 'unlisted', autoUpload = true } = req.body;

  addLog(`Manual video generation requested: Genre [${genreId}], Topic [${topic || 'Default'}]`, "info");

  const pyArgs = [
    path.join(BASE_DIR, 'video_engine', 'generator.py'),
    '--genre', genreId || 'history',
    '--privacy', privacy
  ];
  if (topic) pyArgs.push('--topic', topic);
  if (autoUpload) pyArgs.push('--upload');

  const pyProcess = spawn('python', pyArgs, { cwd: BASE_DIR });

  let outputData = '';
  pyProcess.stdout.on('data', (data) => {
    const text = data.toString().trim();
    outputData += text + '\n';
    addLog(`[Engine] ${text}`, "info");
  });

  pyProcess.stderr.on('data', (data) => {
    const text = data.toString().trim();
    addLog(`[Engine Log] ${text}`, "warning");
  });

  pyProcess.on('close', (code) => {
    if (code === 0) {
      addLog(`Video generation completed successfully for genre [${genreId}]`, "success");
      const videos = readJsonFile(DB_FILE, []);
      res.json({ success: true, latestVideo: videos[0] || null });
    } else {
      addLog(`Video generation process failed with code ${code}`, "error");
      res.status(500).json({ success: false, error: `Engine exited with code ${code}` });
    }
  });
});

// System Logs Endpoint
app.get('/api/logs', (req, res) => {
  res.json(systemLogs);
});

// Continuous Automation Engine Loop Manager
let automationTimer = null;

function runContinuousCycle() {
  if (!automationState.active) return;

  const genres = automationState.selectedGenres;
  if (!genres || genres.length === 0) {
    addLog("No genres selected for continuous automation loop.", "warning");
    return;
  }

  let selectedGenre = genres[0];
  if (automationState.strategy === 'random') {
    selectedGenre = genres[Math.floor(Math.random() * genres.length)];
  } else {
    selectedGenre = genres[automationState.currentGenreIndex % genres.length];
    automationState.currentGenreIndex++;
  }

  addLog(`🤖 [Continuous Loop] Triggering auto-build cycle for Genre: ${selectedGenre.toUpperCase()}`, "info");

  const pyArgs = [
    path.join(BASE_DIR, 'video_engine', 'generator.py'),
    '--genre', selectedGenre,
    '--privacy', automationState.privacy
  ];
  if (automationState.autoUpload) pyArgs.push('--upload');

  const pyProcess = spawn('python', pyArgs, { cwd: BASE_DIR });

  pyProcess.stdout.on('data', (data) => {
    addLog(`[Auto-Engine] ${data.toString().trim()}`, "info");
  });

  pyProcess.stderr.on('data', (data) => {
    addLog(`[Auto-Engine Log] ${data.toString().trim()}`, "warning");
  });

  pyProcess.on('close', (code) => {
    automationState.lastRunTime = new Date().toISOString();
    automationState.totalAutoGenerated++;
    const nextMs = automationState.intervalMinutes * 60 * 1000;
    automationState.nextRunTime = new Date(Date.now() + nextMs).toISOString();

    if (code === 0) {
      addLog(`✨ [Continuous Loop] Video cycle finished successfully! Next run at ${new Date(automationState.nextRunTime).toLocaleTimeString()}`, "success");
    } else {
      addLog(`⚠️ [Continuous Loop] Cycle ended with code ${code}. Rescheduling next run...`, "warning");
    }
  });
}

app.post('/api/automation/toggle', (req, res) => {
  const { active, intervalMinutes, strategy, privacy, autoUpload, selectedGenres } = req.body;

  automationState.active = !!active;
  if (intervalMinutes !== undefined) automationState.intervalMinutes = Math.max(1, parseInt(intervalMinutes));
  if (strategy) automationState.strategy = strategy;
  if (privacy) automationState.privacy = privacy;
  if (autoUpload !== undefined) automationState.autoUpload = !!autoUpload;
  if (selectedGenres) automationState.selectedGenres = selectedGenres;

  if (automationTimer) {
    clearInterval(automationTimer);
    automationTimer = null;
  }

  if (automationState.active) {
    addLog(`▶️ Continuous Automation System STARTED. Running every ${automationState.intervalMinutes} mins.`, "success");
    // Trigger initial run immediately
    runContinuousCycle();
    
    // Schedule repeating timer
    automationTimer = setInterval(() => {
      runContinuousCycle();
    }, automationState.intervalMinutes * 60 * 1000);

    const nextMs = automationState.intervalMinutes * 60 * 1000;
    automationState.nextRunTime = new Date(Date.now() + nextMs).toISOString();
  } else {
    addLog(`⏸️ Continuous Automation System STOPPED.`, "info");
    automationState.nextRunTime = null;
  }

  res.json({ success: true, automation: automationState });
});

// Save YouTube OAuth credentials configuration
app.post('/api/youtube/credentials', (req, res) => {
  const { client_id, client_secret } = req.body;
  if (!client_id || !client_secret) {
    return res.status(400).json({ error: "client_id and client_secret are required" });
  }

  const credentialsData = {
    installed: {
      client_id,
      project_id: "youtube-auto-studio",
      auth_uri: "https://accounts.google.com/o/oauth2/auth",
      token_uri: "https://oauth2.googleapis.com/token",
      auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
      client_secret,
      redirect_uris: ["http://localhost"]
    }
  };

  writeJsonFile(SECRETS_FILE, credentialsData);
  addLog("YouTube OAuth client_secrets.json configured successfully.", "success");
  res.json({ success: true, message: "OAuth client_secrets saved!" });
});

app.post('/api/settings/llm', (req, res) => {
  const { apiKey } = req.body;
  if (!apiKey) return res.status(400).json({ error: "apiKey is required" });
  fs.writeFileSync(ENV_FILE, `LLM_API_KEY=${apiKey}\n`, 'utf8');
  addLog("LLM API Key configured successfully.", "success");
  res.json({ success: true, message: "LLM API key saved!" });
});

app.listen(PORT, () => {
  const url = `http://localhost:${PORT}`;
  addLog(`YouTube Automated Creator Server running on ${url}`, "success");
  
  const startCmd = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'start' : 'xdg-open';
  exec(`${startCmd} ${url}`, (err) => {
    if (err) addLog("Failed to auto-launch browser (you may need to open it manually).", "warning");
  });
});
