import React from 'react';
import { Video, Upload, Layers, Clock, Cpu, ArrowRight, Play, CheckCircle2 } from 'lucide-react';

export default function DashboardOverview({ status, videos, genres, setActiveTab }) {
  const isContinuous = status?.automation?.active;
  const nextRun = status?.automation?.nextRunTime;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
      
      {/* Hero Continuous Status Banner */}
      <div className="glass-panel" style={{ 
        padding: '2rem', 
        background: isContinuous 
          ? 'linear-gradient(135deg, rgba(16, 185, 129, 0.15) 0%, rgba(15, 23, 42, 0.8) 100%)' 
          : 'linear-gradient(135deg, rgba(99, 102, 241, 0.15) 0%, rgba(15, 23, 42, 0.8) 100%)',
        borderColor: isContinuous ? 'rgba(16, 185, 129, 0.4)' : 'rgba(99, 102, 241, 0.4)'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.5rem' }}>
              <div className={isContinuous ? "badge badge-live" : "badge badge-idle"}>
                {isContinuous && <div className="pulse-dot" />}
                {isContinuous ? "CONTINUOUS AUTOMATION ENGINE ONLINE" : "AUTOMATION ENGINE STANDBY"}
              </div>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
                Interval: {status?.automation?.intervalMinutes || 15} minutes
              </span>
            </div>
            <h2 style={{ fontSize: '1.8rem', fontWeight: 700, marginBottom: '0.5rem' }}>
              {isContinuous ? "24/7 Autonomous Content Production Active" : "Ready to Automate Channel Growth"}
            </h2>
            <p style={{ color: 'var(--text-muted)', maxWidth: '700px', fontSize: '0.95rem' }}>
              AutoStudio continuously crafts scripts, synthesizes natural voiceovers, compiles HD vertical & horizontal videos, generates thumbnails, and uploads directly to YouTube across history, kids, languages, trending, and politics genres.
            </p>
          </div>
          
          <button 
            className="btn-primary" 
            onClick={() => setActiveTab('automation')}
            style={{ padding: '0.9rem 1.5rem', fontSize: '0.95rem' }}
          >
            Manage Continuous Engine <ArrowRight size={18} />
          </button>
        </div>

        {isContinuous && nextRun && (
          <div style={{ marginTop: '1.5rem', paddingTop: '1rem', borderTop: '1px solid rgba(255,255,255,0.1)', display: 'flex', gap: '2rem', fontSize: '0.9rem' }}>
            <div>
              <span style={{ color: 'var(--text-muted)' }}>Strategy: </span>
              <strong style={{ textTransform: 'capitalize' }}>{status?.automation?.strategy} Rotation</strong>
            </div>
            <div>
              <span style={{ color: 'var(--text-muted)' }}>Next Video Batch Scheduled: </span>
              <strong style={{ color: '#34D399' }}>{new Date(nextRun).toLocaleTimeString()}</strong>
            </div>
            <div>
              <span style={{ color: 'var(--text-muted)' }}>Total Auto-Created: </span>
              <strong>{status?.automation?.totalAutoGenerated || 0} videos</strong>
            </div>
          </div>
        )}
      </div>

      {/* Metrics Row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '1.5rem' }}>
        
        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
            <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Total Rendered Videos</span>
            <Video size={20} color="#818CF8" />
          </div>
          <h3 style={{ fontSize: '2.2rem', fontWeight: 800 }}>{videos.length}</h3>
          <span style={{ fontSize: '0.8rem', color: '#34D399' }}>HD MP4 files stored in studio</span>
        </div>

        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
            <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>YouTube Uploaded</span>
            <Upload size={20} color="#FF6B6B" />
          </div>
          <h3 style={{ fontSize: '2.2rem', fontWeight: 800 }}>{status?.uploadedCount || 0}</h3>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Auto-tagged & metadata published</span>
        </div>

        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
            <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Configured Genres</span>
            <Layers size={20} color="#FBBF24" />
          </div>
          <h3 style={{ fontSize: '2.2rem', fontWeight: 800 }}>{genres.length}</h3>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>History, Kids, Languages & News</span>
        </div>

        <div className="glass-card">
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
            <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Engine Mode</span>
            <Cpu size={20} color="#34D399" />
          </div>
          <h3 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '0.4rem' }}>
            {isContinuous ? "24/7 Loop" : "Manual & On-Demand"}
          </h3>
          <span style={{ fontSize: '0.8rem', color: isContinuous ? '#34D399' : 'var(--text-muted)' }}>
            {isContinuous ? "Active continuous mode" : "Click Start to enable 24/7"}
          </span>
        </div>

      </div>

      {/* Genres Grid Breakdown & Recent Videos */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
        
        {/* Genre Breakdown */}
        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
            <h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>Genre Distribution & Activity</h3>
            <button className="btn-secondary" style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }} onClick={() => setActiveTab('genres')}>
              View All Genres
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            {genres.map(genre => {
              const count = status?.genreStats?.[genre.id] || 0;
              const percent = videos.length > 0 ? Math.round((count / videos.length) * 100) : 0;
              return (
                <div key={genre.id} style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <div style={{ width: '12px', height: '12px', borderRadius: '50%', background: genre.themeColor }} />
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', marginBottom: '0.3rem' }}>
                      <strong style={{ color: 'var(--text-main)' }}>{genre.name}</strong>
                      <span style={{ color: 'var(--text-muted)' }}>{count} videos ({percent}%)</span>
                    </div>
                    <div style={{ height: '6px', background: 'rgba(255,255,255,0.1)', borderRadius: '3px', overflow: 'hidden' }}>
                      <div style={{ height: '100%', width: `${Math.max(percent, 5)}%`, background: genre.themeColor, borderRadius: '3px' }} />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Recent Generated Videos */}
        <div className="glass-panel" style={{ padding: '1.5rem' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
            <h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>Recent Studio Output</h3>
            <button className="btn-secondary" style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }} onClick={() => setActiveTab('library')}>
              Open Library
            </button>
          </div>

          {videos.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--text-muted)' }}>
              <Video size={40} style={{ marginBottom: '1rem', opacity: 0.5 }} />
              <p>No videos generated yet. Click "Manual Sandbox" or "Start Continuous 24/7" to generate your first video!</p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {videos.slice(0, 4).map(vid => (
                <div key={vid.id} style={{ 
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '1rem', 
                  background: 'rgba(0,0,0,0.3)', 
                  padding: '0.75rem', 
                  borderRadius: '10px' 
                }}>
                  <div style={{ position: 'relative', width: '90px', height: '50px', borderRadius: '6px', overflow: 'hidden', flexShrink: 0, background: 'linear-gradient(135deg, #1E1B4B 0%, #0F172A 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <img 
                      src={`http://localhost:3001${vid.thumbnailFile}`} 
                      alt={vid.title} 
                      style={{ width: '100%', height: '100%', objectFit: 'cover', position: 'absolute', inset: 0 }}
                      onError={(e) => { e.target.style.opacity = '0'; }}
                    />
                    <div style={{ zIndex: 2, background: 'rgba(0,0,0,0.5)', padding: '0.4rem', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <Play size={16} color="white" />
                    </div>
                  </div>

                  <div style={{ flex: 1, minWidth: 0 }}>
                    <h4 style={{ fontSize: '0.9rem', fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                      {vid.title}
                    </h4>
                    <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                      {vid.genreName} • {new Date(vid.createdAt).toLocaleTimeString()}
                    </span>
                  </div>

                  <div className="badge badge-youtube" style={{ fontSize: '0.7rem' }}>
                    <CheckCircle2 size={12} /> {vid.status}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>

    </div>
  );
}
